markdown: kramdown
safe: true
lsi: false
pygments: true
name: "Y-books (양누리 서원)"
description: "양누리 공동체(Yangnuri mission church)의 양누리 서원입니다. 신앙생활에 유익한 도서들을 소개하고 나누는 Yangnuri-Podcast입니다."
url: http://yangnuri3.github.io/
Yangnuri_url: http://cafe.daum.net/yangnuri-ch
sns: 
  twitter: https://twitter.com/o691saza
  facebook: https://www.facebook.com/yangnuri91
podcast:
  feed_url: http://yangnuri3.github.io/podcast.xml
  copyright: Yangnuri
  author: "Yangnuri"
  keyword: "양누리교회,Yangnuri,신승환,설교,교회,양누리,공동체,상담,예수의 핏소리,Y-books,양누리 서원"
  subtitle: "양누리 공동체(Yangnuri mission church)"
  owner_name: seung hwan Shin
  owner_email: o691saza@hanmail.net
  description: "양누리 공동체(Yangnuri mission church)의 양누리 서원입니다. 신앙생활에 유익한 도서들을 소개하고 나누는 Yangnuri-Podcast입니다."
  image: http://yangnuri3.github.io/images/YL3-600-5.jpg
naver_d2:
  image: http://yangnuri3.github.io/images/YL3-600-3.jpg
  url: http://cafe.daum.net/yangnuri-ch
