markdown: kramdown
safe: true
lsi: false
pygments: true
name: "양누리 어울림(Y-books)"
description: ""Yangnuri mission Church" 문화선교의 길을 여는 양누리 어울림(Y-books)입니다. 개혁주의 중심으로 신앙도서 소개와 출판및 판매, 교육, 문화여행,양누리 방송 사역을 합니다. https://m.facebook.com/yangnuri91"
url: http://yangnuri3.github.io/
Yangnuri_url: http://cafe.daum.net/yangnuri-ch
sns: 
  twitter: https://twitter.com/o691saza
  facebook: https://www.facebook.com/yangnuri91
podcast:
  feed_url: http://yangnuri3.github.io/podcast.xml
  copyright: Yangnuri
  author: "Yangnuri"
  keyword: "양누리교회,Yangnuri,신승환,설교,교회,양누리,공동체,상담,예수의 핏소리,Y-books,양누리 서원"
  subtitle: "양누리 공동체(Yangnuri mission church)"
  owner_name: seung hwan Shin
  owner_email: o691saza@hanmail.net
  description: "Yangnuri mission Church" 문화선교의 길을 여는 양누리 어울림(Y-books)입니다. 개혁주의 중심으로 신앙도서 소개와 출판및 판매, 교육, 문화여행,양누리 방송 사역을 합니다. https://m.facebook.com/yangnuri91"
  image: http://yangnuri3.github.io/images/YL3-1400-1.jpg
naver_d2:
  image: http://yangnuri3.github.io/images/YL3-600-3.jpg
  url: http://cafe.daum.net/yangnuri-ch
